[package]
name = "bws"
version = "0.2.1"
edition = "2021"
rust-version = "1.60"
authors = ["Bitwarden Inc"]
license-file = "LICENSE"
repository = "https://github.com/bitwarden/sdk"
homepage = "https://bitwarden.com"
description = """
Bitwarden Secrets Manager CLI
"""
keywords = ["bitwarden", "secrets-manager", "cli"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.0", features = ["derive", "env"] }
tokio = { version = "1.28.2", features = ["rt-multi-thread", "macros"] }
log = "0.4.18"
bitwarden = { path = "../bitwarden", version = "0.2.1" }
env_logger = "0.10.0"
supports-color = "2.0.0"
thiserror = "1.0.40"
serde = "^1.0.163"
serde_json = "^1.0.96"
serde_yaml = "0.9"
bat = { version = "0.23.0", features = ["regex-onig"], default-features = false }
directories = "5.0.1"
color-eyre = "0.6"
toml = "0.7.4"
comfy-table = "^7.0.1"
chrono = { version = "0.4.26", features = ["clock", "std"], default-features = false }
uuid = { version = "^1.3.3", features = ["serde"] }

[dev-dependencies]
tempfile = "3.5.0"
