[package]
name = "bitwarden"
version = "0.2.1"
authors = ["Bitwarden Inc"]
license-file = "LICENSE"
repository = "https://github.com/bitwarden/sdk"
homepage = "https://bitwarden.com"
description = """
Bitwarden Secrets Manager SDK
"""
keywords = ["bitwarden", "secrets-manager"]
edition = "2021"
rust-version = "1.57"

[features]
internal = [] # Internal testing methods

[dependencies]
base64 = "0.21.2"
lazy_static = "1.4.0"
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.96"
serde_qs = "0.12.0"
serde_repr = "0.1.12"
schemars = { version = "0.8", features = ["uuid1", "chrono"] }
log = "0.4.18"
assert_matches = "1.5.0"
thiserror = "1.0.40"
aes = "0.8.2"
cbc = { version = "0.1.2", features = ["alloc"] }
hkdf = "0.12.3"
hmac = "0.12.1"
rsa = "0.9.2"
sha1 = "0.10.5"
sha2 = "0.10.6"
pbkdf2 = { version = "0.12.1", default-features = false }
rand = "0.8.5"
num-bigint = "0.4"
num-traits = "0.2.15"
uuid = { version = "^1.3.3", features = ["serde"] }
chrono = { version = "0.4.0", features = ["serde"] }

# We don't use this directly (it's used by rand), but we need it here to enable WASM support
getrandom = { version = "0.2.9", features = ["js"] }

bitwarden-api-identity = { path = "../bitwarden-api-identity", version = "0.2.0" }
bitwarden-api-api = { path = "../bitwarden-api-api", version = "0.2.0" }

[dev-dependencies]
tokio = { version = "1.28.2", features = ["rt", "macros"] }
wiremock = "0.5.18"
