---
name: Build @bitwarden/sdk-napi

on:
  pull_request:
  push:
    branches:
      - "master"
      - "rc"
      - "hotfix-rc"
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: crates/bitwarden-napi

jobs:
  generate_schemas:
    uses: ./.github/workflows/generate_schemas.yml

  build:
    name: Building @bitwarden/sdk-napi for - ${{ matrix.settings.os }}
    runs-on: ${{ matrix.settings.os || 'ubuntu-latest' }}
    needs: generate_schemas
    strategy:
      fail-fast: false
      matrix:
        settings:
          - os: macos-12
            target: x86_64-apple-darwin
            build: |
              npm run build
              strip -x *.node

          - os: macos-12
            target: aarch64-apple-darwin
            build: |
              npm run build-arm64
              strip -x *.node

          - os: windows-2022
            target: x86_64-pc-windows-msvc
            build: npm run build

          - os: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
            build: |
              set -e &&
              npm run build &&
              strip *.node
    steps:
      - name: Checkout repo
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Setup Node
        uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8 # v3.7.0
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: crates/bitwarden-napi/package-lock.json

      - name: Install rust
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1.0.7
        with:
          profile: minimal
          override: true
          toolchain: stable
          target: ${{ matrix.settings.target }}

      - name: Cache cargo registry
        uses: Swatinem/rust-cache@dd05243424bd5c0e585e4b55eb2d7615cdd32f1f # v2.5.1
        with:
          key: ${{ matrix.settings.target }}-cargo-${{ matrix.settings.os }}

      - name: Retrieve schemas
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        with:
          name: schemas.ts
          path: ${{ github.workspace }}/crates/bitwarden-napi/src-ts/bitwarden_client/

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: ${{ matrix.settings.build }}

      - name: Upload artifact
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        with:
          name: sdk-bitwarden-napi-${{ matrix.settings.target }}
          path: ${{ github.workspace }}/crates/bitwarden-napi/sdk-napi.*.node
          if-no-files-found: error
